import type { Game } from "./games-context"

// DEVELOPER CONFIGURATION: Add your default games and apps here
// You can customize this array to add your own default content
export const DEFAULT_GAMES: Game[] = [
  {
    id: "7",
    title: "Monkey Mart",
    description: "Classic 2048 puzzle game with a jade theme.",
    image: "https://selenite.global.ssl.fastly.net/semag/monkeymart/unnamed.png",
    category: "Puzzle",
    icon: "🎮",
    url: "https://selenite.global.ssl.fastly.net/semag/monkeymart/index.html",
    type: "game",
    isPermanent: true,
  },
  // Example apps
  {
    id: "app_1",
    title: "Achievement Unlocked",
    description: "Simple calculator app for basic math operations.",
    image: "https://selenite.global.ssl.fastly.net/semag/achieveunlocked/icon.png",
    category: "Entertainment",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/achieveunlocked/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_2",
    title: "Achievement Unlocked 2",
    description: "Check the weather forecast for any location.",
    image: "https://selenite.global.ssl.fastly.net/semag/achieveunlocked2/icon.png",
    category: "Utility",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/achieveunlocked2/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_3",
    title: "Bad Ice-Cream",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/badicecream/bad-ice-cream.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/badicecream/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_4",
    title: "Bad Ice-Cream 2",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/badicecream2/bad-ice-cream-2.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/badicecream2/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_5",
    title: "Bad Ice-Cream 3",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/badicecream3/bad-ice-cream-3.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/badicecream3/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_6",
    title: "Bad Time Simulator",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/badtimesimulator/icon-114.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/badtimesimulator/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_7",
    title: "Cut the Rope",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/cuttherope/icon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/cuttherope/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_8",
    title: "Cut the Rope Holiday",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/cuttherope-holiday/Holiday_Gift.webp",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/cuttherope-holiday/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_9",
    title: "CrazyCattle3D",
    description: "Take and organize your notes.",
    image: "https://avatars.githubusercontent.com/u/208939724?s=280&v=4",
    category: "Productivity",
    icon: "?",
    url: "https://yujiandemo.com/",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_10",
    title: "Cookie Clicker",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/cookieclicker/img/perfectCookie.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/cookieclicker/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_11",
    title: "Rocket Bot Royale",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/rocket/cover.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/rocket/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_12",
    title: "Basket Bros",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/basketbros/thumb.jpg",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/basketbros/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_13",
    title: "BitLife",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/bitlife/bitlife.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/bitlife/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_14",
    title: "Celeste",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/celeste/icon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/celeste/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_15",
    title: "Cluster Rush",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/cluster-rush/icon.jpg",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/cluster-rush/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_17",
    title: "Deepest Sword",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/deepestsword/logo.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/deepestsword/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_18",
    title: "Snow Rider 3D",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/snowrider3d/snow.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/snowrider3d/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_19",
    title: "Clicker Heroes",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/clickerheroes/clicker-heroes.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/clickerheroes/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_21",
    title: "Backrooms 2D",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/2d/cover.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/2d/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_22",
    title: "Bouncy Flappy Bird",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/bounce/cover.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/bounce/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_23",
    title: "Drive Mad",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/drivemad/icons/icon-128.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/drivemad/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_24",
    title: "Flappy Bird",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/flappybird/icon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/flappybird/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_25",
    title: "Daydream X",
    description: "Take and organize your notes.",
    image: "https://english.enmar.cl/assets/imgs/logo.png",
    category: "Productivity",
    icon: "?",
    url: "https://english.enmar.cl/",
    type: "app",
    isPermanent: true,
  },
  {
    id: "app_26",
    title: "Baldi's Basics",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/baldis-basics/splash.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/baldis-basics/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_27",
    title: "Dante",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/dante/icon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/dante/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_28",
    title: "Drift Boss",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/drift-boss/icon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/drift-boss/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_29",
    title: "Duck Life 1",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/ducklife1/ducklife1.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/ducklife1/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_30",
    title: "Duck Life 2",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/ducklife2/ducklife2.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/ducklife2/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_31",
    title: "Duck Life 3",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/ducklife3/ducklife3.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/ducklife3/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_32",
    title: "Duck Life 4",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/ducklife4/icon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/ducklife4/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_33",
    title: "Duck Life 5",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/ducklife5/ducklife5.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/ducklife5/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_34",
    title: "Duck Life 6",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/ducklife6/ducklife5.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/ducklife6/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_35",
    title: "Doge Miner",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/dogeminer/img/dogeminer_300x300.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/dogeminer/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_36",
    title: "Flappy Copter",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/flappycopter/cover.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/flappycopter/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_37",
    title: "Geometry Dash Scratch",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/geometrydash/icon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/geometrydash/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_38",
    title: "Geometry Rash",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/geometryrash/icon-114.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/geometryrash/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_39",
    title: "Infinite Craft",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/infi/cover.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/infi/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_40",
    title: "Pizza Tower",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/pizzatower/images/menubg.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/pizzatower/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_41",
    title: "Recoil",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/recoil/cover.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/recoil/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_42",
    title: "Retro Bowl",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/retrobowl/img/icon.jpg",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/retrobowl/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_43",
    title: "Retro Bowl College",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/retrobowlcollege/unnamed.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/retrobowlcollege/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_44",
    title: "Sonic 1",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/sonic/cover.svg",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/sonic/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_45",
    title: "Sonic 2",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/sonic/cover.svg",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/2sonic/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_46",
    title: "Sonic 3",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/3sonic/cover.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/3sonic/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_47",
    title: "Sonic Advance",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/sadvance/cover.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/sadvance/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_48",
    title: "Sonic Advance 2",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/2sadv/cover.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/2sadv/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_49",
    title: "Sonic Advance 3",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/3sadv/cover.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/3sadv/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_50",
    title: "Super Mario 64 DS",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/supermario64ds/supermario64ds.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/supermario64ds/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_51",
    title: "This is the only level",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/thisistheonlylevel/logo.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/thisistheonlylevel/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_52",
    title: "This is the only level 2",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/thisistheonlylevel2/icon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/thisistheonlylevel2/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_53",
    title: "Little Alchemy",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/littlealchemy/images/192-alpha.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/littlealchemy/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_54",
    title: "Moto 3XM",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/motox3m/splash.jpg",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/motox3m/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_55",
    title: "Moto 3XM Pool Party",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/motox3m-pool/splash.jpg",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/motox3m-pool/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_56",
    title: "Moto 3XM Spooky",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/motox3m-spooky/icon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/motox3m-spooky/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_57",
    title: "Moto 3XM Spooky",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/motox3m-winter/download.jpeg",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/motox3m-winter/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_58",
    title: "Helix Jump",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/helixjump/gameIcon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/helixjump/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_59",
    title: "Learn to Fly",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/learntofly/icon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/learntofly/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_60",
    title: "Learn to Fly 2",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/learntofly2/logo.jpg",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/learntofly2/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_61",
    title: "Learn to Fly Idle",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/learntoflyidle/icon.jpg",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/learntoflyidle/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_62",
    title: "POOM",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/poom/cover.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/poom/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_63",
    title: "Slope",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/slope/slope4.jpeg",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/slope/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_64",
    title: "Slope 2",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/slope2/slope-2-logo.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/slope2/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_65",
    title: "Slope 3",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/slope3/cover.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/slope3/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_66",
    title: "Slope Ball",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/slope-ball/icon.jpg",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/slope-ball/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_67",
    title: "Stack",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/stack/icon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/stack/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_68",
    title: "Stickman Climb",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/stickmanclimb/icon.avif",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/stickmanclimb/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_69",
    title: "Stickman Hook (Stickman Swing)",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/stickman-hook/icon.jpg",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/stickman-hook/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_70",
    title: "Super Meat Boy",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/supermeatboy/icon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/supermeatboy/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_71",
    title: "Subway Surfers",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/subway-surfers-ny/NewYorkIcon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/subway-surfers-ny/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_72",
    title: "Five Nights at Freddy's 1",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/fnaf/splash.jpg",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/fnaf/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_73",
    title: "Five Nights at Freddy's 2",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/fnaf2/project/splash.webp",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/fnaf2/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_74",
    title: "Five Nights at Freddy's 3",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/fnaf3/project/splash.webp",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/fnaf3/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_75",
    title: "Five Nights at Freddy's 4",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/fnaf4/project/splash.webp",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/fnaf4/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_76",
    title: "Nut Simulator",
    description: "Take and organize your notes.",
    image: "https://selenite.global.ssl.fastly.net/semag/nutsim/images/icon.png",
    category: "Productivity",
    icon: "?",
    url: "https://selenite.global.ssl.fastly.net/semag/nutsim/index.html",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_77",
    title: "Crazy Games (CLICK ON OPEN NEW TAB)",
    description: "Take and organize your notes.",
    image: "https://imgs.crazygames.com/icon/Originals.svg",
    category: "Productivity",
    icon: "?",
    url: "https://english.enmar.cl/@/daydream/hvtrs8%2F-wuw%2Ccpaxyeaoeq.aoo%2F",
    type: "game",
    isPermanent: true,
  },
  {
    id: "app_78",
    title: "Interstellar",
    description: "Take and organize your notes.",
    image: "https://permits.potomacriversafetycommittee.org/assets/media/favicon/main.png",
    category: "Productivity",
    icon: "?",
    url: "https://permits.potomacriversafetycommittee.org",
    type: "app",
    isPermanent: true,
  },
  {
    id: "app_79",
    title: "AJHS VAULT V8",
    description: "Take and organize your notes.",
    image: "https://ajh8.wine-software.com/header.png",
    category: "Productivity",
    icon: "?",
    url: "https://ajh8.wine-software.com/",
    type: "app",
    isPermanent: true,
  },
  {
    id: "app_80",
    title: "UniUB",
    description: "Take and organize your notes.",
    image: "https://www.google.com/s2/favicons?sz=16&domain_url=https%3A%2F%2Fwww.quizizz.mom%2F%23home",
    category: "Productivity",
    icon: "?",
    url: "https://m.khanacademy.mom",
    type: "app",
    isPermanent: true,
  },
  // Add more default games and apps here
]
